base:
  wandb_enabled: False
main:
  update: False
  update_from: "artifacts/2024/07/01/Run_3/20"
  env_id: 'SafetyPointCircle1-v0'
  render_mode: "human"

  agent:
    name: "CRABS"
    agent_config:
      hidden_size_1: 64
      hidden_size_2: 128

train:
  num_episodes: 100
  max_steps_per_episode: 250
  save_every: 500

test:
  models_dir: "artifacts/2024/07/01/Run_1"
  model_nums: [2000]
  num_runs: 5
  render_mode: 'human'
  max_steps_per_episode: 500



